//
//  JLIFactoryTypes.cpp
//  JLIGameEngineTest
//
//  Created by James Folk on 12/26/14.
//  Copyright (c) 2014 James Folk. All rights reserved.
//

#include "JLIFactoryTypes.h"

namespace njli
{
  const u32 njliRenderCategoryValues[32] = {
      JLI_BIT_CATEGORY_1,  JLI_BIT_CATEGORY_2,  JLI_BIT_CATEGORY_3,
      JLI_BIT_CATEGORY_4,  JLI_BIT_CATEGORY_5,  JLI_BIT_CATEGORY_6,
      JLI_BIT_CATEGORY_7,  JLI_BIT_CATEGORY_8,  JLI_BIT_CATEGORY_9,
      JLI_BIT_CATEGORY_10, JLI_BIT_CATEGORY_11, JLI_BIT_CATEGORY_12,
      JLI_BIT_CATEGORY_13, JLI_BIT_CATEGORY_14, JLI_BIT_CATEGORY_15,
      JLI_BIT_CATEGORY_16, JLI_BIT_CATEGORY_17, JLI_BIT_CATEGORY_18,
      JLI_BIT_CATEGORY_19, JLI_BIT_CATEGORY_20, JLI_BIT_CATEGORY_21,
      JLI_BIT_CATEGORY_22, JLI_BIT_CATEGORY_23, JLI_BIT_CATEGORY_24,
      JLI_BIT_CATEGORY_25, JLI_BIT_CATEGORY_26, JLI_BIT_CATEGORY_27,
      JLI_BIT_CATEGORY_28, JLI_BIT_CATEGORY_29, JLI_BIT_CATEGORY_30,
      JLI_BIT_CATEGORY_31};
}
