
message(STATUS "Platform is linux for project")

find_package(OpenGL REQUIRED)
if(OPENGL_FOUND)
  MESSAGE(STATUS "OPENGL_INCLUDE_DIR ${OPENGL_INCLUDE_DIR}")
  MESSAGE(STATUS "OPENGL_LIBRARIES ${OPENGL_LIBRARIES}")
  list(APPEND EXTRA_LIBS "${OPENGL_LIBRARIES}")
  list(APPEND ${CMAKE_PROJECT_NAME}_THIRDPARTY_INCLUDE_DIRECTORES "${OPENGL_INCLUDE_DIR}")
endif()

