SOURCE_GROUP("INCLUDE" FILES ${INCLUDE_FILES} )
SOURCE_GROUP("SOURCE\\engine" FILES ${SOURCE_FILES} )
SOURCE_GROUP("SOURCE\\main" FILES ${MAIN_FILES} )
SOURCE_GROUP("RESOURCE" FILES ${RESOURCE_FILES} )

