# General source files
file(GLOB_RECURSE SOURCE_FILES
  ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/njli/*.c
  ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/njli/*.cpp
  ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/njli/*.cxx
  )

file(GLOB MAIN_FILES
  ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/njli/platform/main.cpp
  )

file(GLOB_RECURSE INCLUDE_FILES
  ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/njli/*.h
  ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/njli/*.hpp
  ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/njli/*.hxx
  )
