set(${CMAKE_PROJECT_NAME}_LUA_SWIG_ENABLED_BY_DEFAULT ON)
set(${CMAKE_PROJECT_NAME}_LUA_SWIG ${${CMAKE_PROJECT_NAME}_LUA_SWIG_ENABLED_BY_DEFAULT} CACHE BOOL "Build the swig module for ${CMAKE_PROJECT_NAME}")

list(APPEND CMAKE_MODULE_PATH "${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/cmake")

macro(LUA_BULLET_SWIG)
  set(CMAKE_SWIG_FLAGS "")

  file(GLOB_RECURSE LUA_SWIG_SOURCE_FILES
    ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig.in/script/thirdparty/bullet3/*.swg
    )

  list(APPEND LUA_SWIG_SOURCE_FILES
    "${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig.in/script/thirdparty/bullet3/bullet3.i" 
  )

  file(GLOB_RECURSE NJLIC_INCLUDE_SWIG_SOURCE_FILES
    ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig.in/script/njli/include/*.swg
    )
  list(APPEND LUA_SWIG_SOURCE_FILES
    "${NJLIC_INCLUDE_SWIG_SOURCE_FILES}" 
  )

  SUBDIRLIST(SUBDIRS "${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig.in/script/thirdparty/bullet3" SWIGIN_SCRIPTS_INCLUDE_DIRECTORY_LIST)

  set(${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-includeall")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-fcompact")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-fvirtual")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-v")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-w201")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-w312")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-ignoremissing")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-cpperraswarn")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-DBT_INFINITY")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-DSWIG_TYPE_TABLE=myprojectname")

  foreach(_SWIG_SOURCE_FILE ${LUA_SWIG_SOURCE_FILES})
    MESSAGE(STATUS "_SWIG_SOURCE_FILE ${_SWIG_SOURCE_FILE}")
    set_property(SOURCE ${_SWIG_SOURCE_FILE} PROPERTY SWIG_FLAGS ${${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS})
    set_property(SOURCE ${_SWIG_SOURCE_FILE} PROPERTY CPLUSPLUS ON)
    set_property(SOURCE ${_SWIG_SOURCE_FILE} PROPERTY SWIG_INCLUDE_DIRECTORIES "${SWIGIN_SCRIPTS_INCLUDE_DIRECTORY_LIST}")
  endforeach()

  include_directories("${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig.in/script/thirdparty/bullet3" ${SWIGIN_SCRIPTS_INCLUDE_DIRECTORY_LIST})

  foreach(_SWIGIN_SCRIPTS_INCLUDE_DIRECTORY ${SWIGIN_SCRIPTS_INCLUDE_DIRECTORY_LIST})
    MESSAGE(STATUS "_SWIGIN_SCRIPTS_INCLUDE_DIRECTORY ${_SWIGIN_SCRIPTS_INCLUDE_DIRECTORY}")
  endforeach()

  swig_add_library(
    ${CMAKE_PROJECT_NAME}-lua-swig-bullet3-static
    TYPE STATIC
    LANGUAGE lua
    SOURCES "${LUA_SWIG_SOURCE_FILES}"
    OUTPUT_DIR ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig/lua/bullet3
    OUTFILE_DIR ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig/lua/bullet3
    )
  set_directory_properties(PROPERTIES ADDITIONAL_MAKE_CLEAN_FILES ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig/lua/bullet3)

  list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS BULLET_SWIG=1)
  target_compile_definitions(${CMAKE_PROJECT_NAME}-lua-swig-bullet3-static PUBLIC ${${CMAKE_PROJECT_NAME}_DEFINITIONS})

  TARGET_LINK_LIBRARIES(${CMAKE_PROJECT_NAME}-lua-swig-bullet3-static ${CMAKE_PROJECT_NAME}-static)

  list(APPEND EXTRA_LIBS ${CMAKE_PROJECT_NAME}-lua-swig-bullet3-static)
  list(APPEND INTERFACE_FILES ${LUA_SWIG_SOURCE_FILES})
endmacro()

macro(LUA_NJLI_SWIG)
  set(CMAKE_SWIG_FLAGS "")

  file(GLOB_RECURSE LUA_SWIG_SOURCE_FILES
    ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig.in/script/njli/*.swg
    )

  list(APPEND LUA_SWIG_SOURCE_FILES
    "${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig.in/script/njli/njlic.i" 
  )

  SUBDIRLIST(SUBDIRS "${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig.in/script/njli" SWIGIN_SCRIPTS_INCLUDE_DIRECTORY_LIST)

  set(${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-includeall")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-fcompact")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-fvirtual")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-v")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-w201")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-w312")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-ignoremissing")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-cpperraswarn")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-DBT_INFINITY")
  list(APPEND ${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS "-DSWIG_TYPE_TABLE=myprojectname")

  foreach(_SWIG_SOURCE_FILE ${LUA_SWIG_SOURCE_FILES})
    MESSAGE(STATUS "_SWIG_SOURCE_FILE ${_SWIG_SOURCE_FILE}")
    set_property(SOURCE ${_SWIG_SOURCE_FILE} PROPERTY SWIG_FLAGS ${${CMAKE_PROJECT_NAME}_LUA_SWIG_FLAGS})
    set_property(SOURCE ${_SWIG_SOURCE_FILE} PROPERTY CPLUSPLUS ON)
    set_property(SOURCE ${_SWIG_SOURCE_FILE} PROPERTY SWIG_INCLUDE_DIRECTORIES "${SWIGIN_SCRIPTS_INCLUDE_DIRECTORY_LIST}")
  endforeach()

  include_directories("${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig.in/script/njli" ${SWIGIN_SCRIPTS_INCLUDE_DIRECTORY_LIST})

  foreach(_SWIGIN_SCRIPTS_INCLUDE_DIRECTORY ${SWIGIN_SCRIPTS_INCLUDE_DIRECTORY_LIST})
    MESSAGE(STATUS "_SWIGIN_SCRIPTS_INCLUDE_DIRECTORY ${_SWIGIN_SCRIPTS_INCLUDE_DIRECTORY}")
  endforeach()

  swig_add_library(
    ${CMAKE_PROJECT_NAME}-lua-swig-njlic-static
    TYPE STATIC
    LANGUAGE lua
    SOURCES "${LUA_SWIG_SOURCE_FILES}"
    OUTPUT_DIR ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig/lua/njlic
    OUTFILE_DIR ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig/lua/njlic
    )
  set_directory_properties(PROPERTIES ADDITIONAL_MAKE_CLEAN_FILES ${${CMAKE_PROJECT_NAME}_REPO_DIRECTORY}/swig/lua/bullet3)

  list(APPEND ${CMAKE_PROJECT_NAME}_DEFINITIONS NJLIC_SWIG=1)
  target_compile_definitions(${CMAKE_PROJECT_NAME}-lua-swig-njlic-static PUBLIC ${${CMAKE_PROJECT_NAME}_DEFINITIONS})

  TARGET_LINK_LIBRARIES(${CMAKE_PROJECT_NAME}-lua-swig-njlic-static ${CMAKE_PROJECT_NAME}-static)

  list(APPEND EXTRA_LIBS ${CMAKE_PROJECT_NAME}-lua-swig-njlic-static)
  list(APPEND INTERFACE_FILES ${LUA_SWIG_SOURCE_FILES})
endmacro()

if(${CMAKE_PROJECT_NAME}_LUA_SWIG)
  if(${CMAKE_VERSION} VERSION_LESS "3.11")
    message("Please consider to switch to CMake 3.11 in order to use SWIG")
  else()
    find_package(SWIG REQUIRED)

    if(${SWIG_FOUND})
      MESSAGE(STATUS "SWIG_FOUND ${SWIG_FOUND}")
      MESSAGE(STATUS "SWIG_DIR ${SWIG_DIR}")
      MESSAGE(STATUS "SWIG_EXECUTABLE ${SWIG_EXECUTABLE}")
      MESSAGE(STATUS "SWIG_VERSION ${SWIG_VERSION}")

      include(${SWIG_USE_FILE})

      LUA_NJLI_SWIG()
      LUA_BULLET_SWIG()

    endif()
  endif()
endif()
